import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import Products from '@/components/Products';


export default function Home() {
  return (
    <>
      <Head>
        <title>Corre 012</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header/>
      <section>
        <Banner/>
      </section>

      <section>
        <Products/>
      </section>
      
    </>
  );
}
